FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV LANG=en_US.utf8

COPY ocs-operator /usr/local/bin/ocs-operator
COPY metrics-exporter /usr/local/bin/metrics-exporter
COPY *rules*.yaml /ocs-prometheus-rules/
COPY *quickstart*.yaml /quickstarts/
USER 1001

ENTRYPOINT [ "/usr/local/bin/ocs-operator" ]
